apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-counter
  annotations:
    app.openshift.io/connects-to: |
      [{"apiVersion":"apps/v1","kind":"StatefulSet","name":"redis"}]
  labels:
    project: counter
spec:
  selector:
    matchLabels:
      project: counter
      app: counter
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        project: counter
        app: counter
        release: {{.Release.Name}}
    spec:
      containers:
        - name: main
          image: ondrejsika/counter
          startupProbe:
            httpGet:
              path: /
              port: 80
          env:
            - name: REDIS
              value: {{.Release.Name}}-redis
          ports:
            - containerPort: 80
